name: Go
on:
  - push
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Do test
      run: make ci-check

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest

