name: Go
on: [push]
jobs:

  build:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
        golangcilint-version: [1.45.2]
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get go toolchains
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v${{ matrix.golangcilint-version }}
        sudo cp $GOPATH/bin/golangci-lint /usr/bin/
      env:
        GOPATH: /home/runner/work/sesstok/go

    - name: Do test
      run: make check
      env:
        GOPATH: /home/runner/work/sesstok/go

